### ISSUE TITLE
The function in the texture naming does not need to be the directory the image!

### ISSUE THREAD

**Issue by ryandakid** [mountainflaw/modconv_2#17]
When using assembly, a name followed by a colon indicates that a function is being created.

In a model file, when it names the functions for the .rgba file, it calls it C:\<Whatever Directory>

This means that is creating a function called C, and the rest of the directory name is a syntax error. This is a HUGE issue, especially if you want to use textures.

**Comment by mountainflaw** [comment]
Are you using an older version? I changed it to use generic names a long time ago. https://github.com/mountainflaw/modconv_2/blob/master/src/f3d.cxx#L432

**Comment by ryandakid** [comment]
I am not sure....
