### ISSUE TITLE
Build script hangs on "[INFO] Building modconv2..."

### ISSUE THREAD

**Issue by someone2639** [mountainflaw/modconv_2#18]
(Windows 10 Build 18965 with Ubuntu on WSL2)

Both ASSIMP and g++-8 are installed and being utilized (no errors when including filesystem), but when building modconv, it hangs on "[INFO] Building modconv2..." for hours with no signs of progress. The build folder is empty after canceling the operation, and everything in the folder has full RWX permissions.

**Comment by CrashOveride95** [comment]
I thought g++11 was required?

**Comment by mountainflaw** [comment]
> I thought g++11 was required?

no, just g++-8.

**Comment by someone2639** [comment]
Apparently this might have been because i was selecting text (which famously pauses all terminal output 💀)

**Comment by CrashOveride95** [comment]
congrats this is the oldest issue necroreply ive ever seen
